---

fail_fast: false

repos:
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    sha: 1.3.1
    hooks:
      - id: forbid-binary
      - id: git-check  # check whitespace and conflict markers
      - id: git-dirty
      - id: shellcheck

  - repo: https://github.com/adrienverge/yamllint.git
    sha: v1.10.0
    hooks:
      - id: yamllint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: detect-private-key

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.4
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs
